"""new

Revision ID: 36d76ae7755d
Revises: d151330c9bcb
Create Date: 2025-01-26 19:21:28.257376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36d76ae7755d'
down_revision = 'd151330c9bcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('event_description', sa.String(length=140), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wants_to_be_organiser', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('organisation', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('organisation')
        batch_op.drop_column('wants_to_be_organiser')

    with op.batch_alter_table('marker', schema=None) as batch_op:
        batch_op.drop_column('event_description')
        batch_op.drop_column('event_time')

    # ### end Alembic commands ###
