"""empty message

Revision ID: 425b5b1d2097
Revises: 3d4f17d8491d
Create Date: 2025-01-20 10:58:05.207518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '425b5b1d2097'
down_revision = '3d4f17d8491d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_time', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('event_description', sa.String(length=140), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marker', schema=None) as batch_op:
        batch_op.drop_column('event_description')
        batch_op.drop_column('event_time')

    # ### end Alembic commands ###
