"""empty message

Revision ID: 6d2a5e541b2d
Revises: 
Create Date: 2025-02-04 21:08:39.519386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d2a5e541b2d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Marker', schema=None) as batch_op:
        batch_op.drop_column('end_time')
        batch_op.drop_column('date_occurring')
        batch_op.drop_column('recurring')
        batch_op.drop_column('start_time')
        batch_op.drop_column('all_day')
        batch_op.drop_column('days_recurring')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Marker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('days_recurring', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('all_day', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('start_time', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('recurring', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('date_occurring', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
